### ISSUE TITLE
Chrome 96リリースノートまとめ: Support calc(`<number>`) where only accepts `<integer>`の例が例になっていない

### ISSUE THREAD

**Issue by myakura** [cybozu/frontend-expert#42]
https://cybozu.github.io/frontend-expert/posts/release-chrome-96

このエントリの一部なのですが、

https://github.com/cybozu/frontend-expert/blob/7dd891dd717cb7ea854173483460b9c319b962ab/data/posts/release-chrome-96.md?plain=1#L244-L257

> cssの`calc()`関数でintegerしか受け取らないような場所でもnumberを指定できるようになりました。
> もっとも近い整数に丸められます。

この説明はあっているのですが

> 例えば、下記はいずれも`width: 0px`と同義です。
> 
> ```css
> .example {
>     width: calc(5px - 10px);
>     width: calc(-5px);
>     width: 0px;
> }
> ```

この例はそれを説明していません（`width`は`<length-percentage>`系の値をとって`<length>`に解決するので、`<integer>`と`<number>`はとらない）。
たぶん仕様書からひっぱってきたものと思うんですが、これはnumberをintegerにまるめる仕様の例ではないんですよね。

**Comment by nus3** [comment]
@myakura 
issueありがとうございます!
仕様のexampleを勘違いして使っていました..
すみません

https://github.com/cybozu/frontend-expert/pull/50
でサンプルコードをinteger型の`column-width`に変えました!
ご報告ありがとうございました!!
