### ISSUE TITLE
RSSフィードの&がエスケープされていない

### ISSUE THREAD

**Issue by hosht** [cybozu/frontend-expert#71]
はじめまして、こちらのサイトのRSSフィードを購読しようとしたところエラーが発生しました。
https://cybozu.github.io/frontend-expert/feeds/atom.xml のURLをChromeで直接開いたところ、
>error on line 1 at column 2412: EntityRef: expecting ';'

と表示されましたのでおそらくこちらの記事タイトルに含まれる`&`がエスケープされておらずエラーになっていると考えられます。
https://github.com/cybozu/frontend-expert/blob/main/data/posts/frontendWeekly-And-Monthly.md

**Comment by nakajmg** [comment]
@hosht 
報告ありがとうございます！

確認して近いうちに修正します💁🏻‍♀️

**Comment by nakajmg** [comment]
@hosht 
修正しましたのでよければご確認ください！

https://cybozu.github.io/frontend-expert/feeds/atom.xml

ありがとうございました 🙏

**Comment by hosht** [comment]
@nakajmg 
RSSフィードの表示、購読問題ありませんでした
迅速な対応ありがとうございました！
